name: Test Compile
on: [ push, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
          cache: 'gradle'
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build Soak
        run: ./gradlew build
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: Soak-Vanilla.zip
          path: plugin/build/libs/*.jar

