name: Test Compile
on: [ push, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'
      - name: Make Forge gradle executable
        run: chmod +x ./ForgeBuild/gradlew
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Show Java Home
        run: echo $JAVA_HOME
      - name: Build forge cache
        run: ./gradlew build
        working-directory: ./ForgeBuild
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Show java 11 home
        run: echo $JAVA_HOME
      - name: Build Soak
        run: ./gradlew soak-plugin:build

